alias ls='ls --color=auto'
alias l='ls -l'
alias ll='ls -lA'
alias la='ls -A'
alias gst='git status'
alias ga='git add'
alias gc='git commit -m'
alias gp='git pull && git push'
alias getch='git fetch'
alias gull='git pull'
alias gush='git push'
alias gb='git branch'
alias gco='git checkout'
alias gd='git diff'
